// src/config/limits.config.ts

export const LIMITS = {
  // ─── Webhook Processing ───
  WEBHOOK_TIMEOUT_MS: 4500,
  WEBHOOK_MAX_RETRIES: 3,
  WEBHOOK_MAX_PAYLOAD_SIZE_BYTES: 1_000_000, // 1MB

  // ─── Agent Execution ───
  AGENT_MAX_EXECUTION_MS: 30_000,
  AGENT_MAX_LLM_TOKENS_PER_CALL: 4096,
  AGENT_MAX_TOOL_CALLS_PER_RUN: 5,
  AGENT_MIN_CONFIDENCE_THRESHOLD: 0.3,

  // ─── Rate Limiting ───
  SHOPIFY_API_CALLS_PER_SECOND: 2,
  KLAVIYO_API_CALLS_PER_SECOND: 3,
  GORGIAS_API_CALLS_PER_SECOND: 2,
  AGENT_ACTIONS_PER_MINUTE_PER_STORE: 10,

  // ─── Queue ───
  QUEUE_MAX_RETRIES: 3,
  QUEUE_MAX_BATCH_SIZE: 100,
  QUEUE_CONSUMER_TIMEOUT_MS: 25_000,
  QUEUE_DEAD_LETTER_THRESHOLD: 3,

  // ─── Data Retention ───
  PROCESSED_EVENTS_RETENTION_DAYS: 7,
  AGENT_RUNS_RETENTION_DAYS: 90,
  EVENTS_RETENTION_DAYS: 30,
  DEAD_LETTER_RETENTION_DAYS: 30,
  DAILY_METRICS_RETENTION_DAYS: 365,

  // ─── Pagination ───
  DEFAULT_PAGE_SIZE: 50,
  MAX_PAGE_SIZE: 200,
  MIN_PAGE_SIZE: 1,

  // ─── Budget ───
  DEFAULT_DAILY_LLM_BUDGET_USD: 25,
  DEFAULT_MONTHLY_LLM_BUDGET_USD: 500,
  ABSOLUTE_MAX_DAILY_LLM_BUDGET_USD: 100,
  ABSOLUTE_MAX_MONTHLY_LLM_BUDGET_USD: 2000,

  // ─── Vector Store ───
  VECTOR_MAX_DOCUMENTS_PER_NAMESPACE: 50_000,
  VECTOR_MAX_CONTENT_LENGTH: 32_000,
  VECTOR_SEARCH_DEFAULT_LIMIT: 10,
  VECTOR_SEARCH_MAX_LIMIT: 50,
  VECTOR_MIN_SIMILARITY: 0.5,
  VECTOR_DEFAULT_SIMILARITY: 0.7,

  // ─── Memory Cache ───
  MEMORY_CACHE_TTL_MS: 60_000,
  MEMORY_CACHE_MAX_SIZE: 10_000,
  AUTH_CACHE_TTL_MS: 60_000,

  // ─── Sync ───
  SYNC_MAX_ORDERS_PER_BATCH: 250,
  SYNC_DEFAULT_LOOKBACK_DAYS: 30,
  SYNC_RATE_LIMIT_DELAY_MS: 500,
} as const;

// Type for accessing limits
export type LimitKey = keyof typeof LIMITS;

export function getLimit(key: LimitKey): number {
  return LIMITS[key];
}
